#!/bin/bash
#PBS -N glycine_max_RNA_seq
#PBS -M chensc2008@gmail.com
#PBS -m ae 
#PBS -o pal_finder_RNAseq.o
#PBS -e pal_finder_RNAseq.err
#PBS -l walltime=240:00:00
#PBS -l pmem=1gb
#PBS -l nodes=1:ppn=16

cd $PBS_O_WORKDIR


############################################################
# pal finder v00204
# by  Shichao chen
#############################################################

module load primer3

perl pal_finder_v0.02.04.pl My_config_RNA_seq_SRR20335ONE.txt