#!/bin/bash
#PBS -N 454_raw_all
#PBS -M chensc2008@gmail.com
#PBS -m ae 
#PBS -o pal_finder_454_raw_all.o
#PBS -e pal_finder_454_raw_all.err
#PBS -l walltime=64:00:00
#PBS -l pmem=2gb
#PBS -l nodes=1:ppn=8

cd $PBS_O_WORKDIR


############################################################
# pal finder v00204
#
############################################################

module load primer3

perl pal_finder_v0.02.04.pl My_config_454_raw_all.txt