#!/bin/bash
#PBS -N Genome_8core
#PBS -M chensc2008@gmail.com
#PBS -m ae 
#PBS -o pal_finder_genome.o
#PBS -e pal_finder_genome.err
#PBS -l walltime=64:00:00
#PBS -l pmem=2gb
#PBS -l nodes=1:ppn=8

cd $PBS_O_WORKDIR


############################################################
# pal finder v00204
#
################

module load primer3

perl pal_finder_v0.02.04.pl My_config_whole_genom_8_core.txt